### ISSUE TITLE
Feature request: Hide certain network interfaces from showing in the app

### ISSUE THREAD

**Issue by alsoGAMER** [nokyan/resources#22]
Hi there, i love this app already, though i wish it was possible to hide certain network interfaces from showing up in the app, especially when, like me, you have a bunch of virtual interfaces created by/for docker containers.

![image](https://github.com/nokyan/resources/assets/35269770/8b6d97c3-1337-490b-aeae-eb9c5a09199f)

My solution would be to implement a section in the settings pane named "Network Interfaces" with all of the ifaces/vifaces and a tickbox to the left.

![mockup example](https://github.com/nokyan/resources/assets/35269770/118badcd-2d1a-4f17-8d9f-80548f4591d8)
eg. something like this (which i know it's bad, but i'm not someone that knows how to make mockups, so....)

**Comment by nokyan** [comment]
Hi, thanks for raising the issue!
I didn't know about Docker's virtual network interfaces so I didn't consider them. I'll put an option for something like that on my to-do list, maybe a setting that hides known virtual adapters?

**Comment by alsoGAMER** [comment]
That could work too, everything that starts with veth, br or vmbr can be considered a virtual interface.

**Comment by alsoGAMER** [comment]
![image](https://github.com/nokyan/resources/assets/35269770/07d86bf3-f483-46fe-9bcc-42cb90033306)
@nokyan it seems the issue wasn't actually fixed even though it should be...
i'm on v1.2.0-7e03189

**Comment by nokyan** [comment]
> ![image](https://user-images.githubusercontent.com/35269770/279390888-07d86bf3-f483-46fe-9bcc-42cb90033306.png) @nokyan it seems the issue wasn't actually fixed even though it should be... i'm on v1.2.0-7e03189

Thanks for noticing. I believe I found the issue, it'll be fixed with Resources 1.2.1 in a few days. :)

**Comment by shrugal** [comment]
Docker network interfaces (`docker0` and `br-xyz`) still show up for me, even with virtual network interfaces disabled:

![Bildschirmfoto vom 2024-05-05 00-28-00](https://github.com/nokyan/resources/assets/710525/0d57e032-f999-4d41-9132-924b24ecdf23)

**Comment by nokyan** [comment]
> Docker network interfaces (`docker0` and `br-xyz`) still show up for me, even with virtual network interfaces disabled:
> 
> ![Bildschirmfoto vom 2024-05-05 00-28-00](https://private-user-images.githubusercontent.com/710525/327978477-0d57e032-f999-4d41-9132-924b24ecdf23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTY2NTgsIm5iZiI6MTcxNDg5NjM1OCwicGF0aCI6Ii83MTA1MjUvMzI3OTc4NDc3LTBkNTdlMDMyLWY5OTktNGQ0MS05MTMyLTkyNGIyNGVjZGYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwODA1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTZmNjExZjQzOGM1Njc1ODI5NGIwZWZhYTllYTE2MjY3YTViZWY0YzMyN2ExMDZhMTY2MTUzZTE5NDlkNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7yG1O--N-sHlo46vFlcuWXbQS2zln6ZCjzMxVyuo_6c)
> 
> I'm on v1.4.0.

I merged a fix, it will be deployed with the next release

**Comment by TI34H** [comment]
![Screenshot From 2024-11-29 22-53-17](https://github.com/user-attachments/assets/ee4a5559-4b6b-4d04-bb35-40fe081ee9b0)
Request to support hiding virtual network interfaces like TUN

**Comment by nokyan** [comment]
> ![Screenshot From 2024-11-29 22-53-17](https://private-user-images.githubusercontent.com/168891049/391125249-ee4a5559-4b6b-4d04-bb35-40fe081ee9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTgyMjEsIm5iZiI6MTczMjkxNzkyMSwicGF0aCI6Ii8xNjg4OTEwNDkvMzkxMTI1MjQ5LWVlNGE1NTU5LTRiNmItNGQwNC1iYjM1LTQwZmUwODFlZTliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQyMjA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzU0NWUxNjg3OThmMzM0MTc0YTZiZWRiZTI1MWVkMGJlNjE4MDg3ZDBiZWY2MTQ0MWI3YzZiMmI0NDY0ZTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.imkHLYB8i_8q1uWX53tdLBLhfQWFF2I5HanMvEmB_9M) Request to support hiding virtual network interfaces like TUN.

Done as of commit [b39e24f](https://github.com/nokyan/resources/commit/b39e24f7d85ae747271ba770de6c1db35988b7ae).

**Comment by TI34H** [comment]
Thank you for your quick reply. I have built the latest source code and can now successfully hide the tun network interface.

**Comment by TI34H** [comment]
![Screenshot From 2024-11-30 16-35-53](https://github.com/user-attachments/assets/2405c948-e71c-436a-be95-116f5948c1d3)

I'm currently using another [proxy software](https://github.com/daeuniverse/dae) with a virtual network interface called dae0. Can it also support hiding?It would only require adding one line of code:
("dae", InterfaceType::Vpn)

**Comment by nokyan** [comment]
> ![Screenshot From 2024-11-30 16-35-53](https://private-user-images.githubusercontent.com/168891049/391223491-2405c948-e71c-436a-be95-116f5948c1d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjQ3ODAsIm5iZiI6MTczMjk2NDQ4MCwicGF0aCI6Ii8xNjg4OTEwNDkvMzkxMjIzNDkxLTI0MDVjOTQ4LWU3MWMtNDM2YS1iZTk1LTExNmY1OTQ4YzFkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMTAxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmI4YzllZDM5YmRhYmJkMzAyZmRmNTc1YjQ0ZjQ1MjhlNzVkYmYyZmQ1NjI1NTE1MmIzYWUzMTBlMTVlYWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6IjfmYnQwrb4XAnOHAXjAVKKof_VFpKTzjx7w_Uq1xU)
> 
> I'm currently using another [proxy software](https://github.com/daeuniverse/dae) with a virtual network interface called dae0. Can it also support hiding?It would only require adding one line of code: ("dae", InterfaceType::Vpn)

Done as of [6d16bfd](https://github.com/nokyan/resources/commit/6d16bfd3c314f39b12c4f5e4e97e3ec362096586)

**Comment by TI34H** [comment]
Thank you for quickly implementing this feature. The modification to support hiding the virtual network interface works perfectly for my use case. I appreciate your prompt and helpful response.
