### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by gmagic** [nokyan/resources#45]
After app start-up i see 1Gb+ of ram usage.
![image](https://github.com/nokyan/resources/assets/35816519/5580143c-3c46-42ca-a355-81e02f218b00)

**Comment by tim77** [comment]
In my case at startup app uses 125MB and keep growing to 500MB and more.

- Build: Flathub version;
- NVIDIA drivers.

**Comment by tim77** [comment]
After some observations i found that seems like 1.03GB is maximum limit and after this point it stops growing. So this doesn't look like memory leak. But this to much i believe for and would be nice to reduce somehow memory consumption.
![Снимок экрана от 2023-10-19 16-33-38](https://github.com/nokyan/resources/assets/5614476/725d4395-2979-485b-beb4-96d0cdfea0cc)

**Comment by jenavarro** [comment]
Also happens to me. Memory usage went from around 150MB when started then 
Resources                             net.nokyan.Resources                 1.1.0   stable      system
![image](https://github.com/nokyan/resources/assets/7155108/1959e977-83cc-4e9f-b99b-f9f10b5fa4ea)

**Comment by nokyan** [comment]
Thank you all very much for the reports, I'll try to find out why that happens :)

**Comment by liz-desartiges** [comment]
I have noticed higher ram usage that what've been reported here : 1.73GB of ram used by ressources
![image](https://github.com/nokyan/resources/assets/19488257/ac193bb9-7f74-4d6c-9d60-c02966ef3171)

**Comment by nokyan** [comment]
Just a quick update: I now know what seems to cause the leak and have opened a PR (#128) for it. Unfortunately I haven't yet found out how to get rid of it. I hope I'll figure something out before releasing 1.3.

**Comment by nokyan** [comment]
Potentially great news: I believe it's fixed now. Interestingly though, I probably fixed it on accident at some point and introduced another one with the right click context menus. In the `memory-leak-fix` branch I've removed the context menus again, which for me kept memory usage very much under control. I'd appreciate if someone could test it as well. :)

**Comment by outusuke** [comment]
It hasn't been fixed yet, I still see it consuming GB after being open for a while

**Comment by nokyan** [comment]
I've experienced increased memory consumption as well, but I frankly have not a single clue why that is.

**Comment by bbktsk** [comment]
Almost 4GB memory consumed after cca 20 hours. Version 1.5.0 from flatpak, Ubuntu 22.04 with regolith desktop, i3wm, intel integrated gfx, two 4k displays. 
![image](https://github.com/nokyan/resources/assets/9937868/e240ad41-f864-409a-97d3-0552d7afb2ba)

**Comment by nokyan** [comment]
I've changed some internal stuff regarding apps and processes, could you check out the `appscontext-restructure` branch? In my testing memory usage and leakage is reduced.

**Comment by jojo2357** [comment]
I'm definitely getting some reduction, however that is comparing the flatpak vers to the builder vers so not certain that it will be permanent

**Comment by bbktsk** [comment]
Can you please make the flakpak for that test branch available? My rust-fu is not strong enough to build it for myself, but I'll be happy to test.

**Comment by nokyan** [comment]
Just a heads-up: the branch is merged now so you can just test `main`.

@jojo2357 
That's good to see! To my knowledge, if anything, the Builder version should perform worse as it isn't as optimized (by the compiler) as the Flatpak production version.

@bbktsk 
I'll look into it but you shouldn't need any Rust to build the flatpak for yourself. In fact, it should be just three commands. :)
```sh
flatpak install org.gnome.Sdk//46 org.freedesktop.Sdk.Extension.rust-stable//23.08 org.gnome.Platform//46 org.freedesktop.Sdk.Extension.llvm18//23.08
flatpak-builder --user flatpak_app build-aux/net.nokyan.Resources.Devel.json
flatpak-builder --run flatpak_app build-aux/net.nokyan.Resources.Devel.json resources
```

**Comment by jojo2357** [comment]
After 2 days on 1.6.0 im seeing 0.5GiB memory used. Progress for sure, but not solved.

**Comment by nokyan** [comment]
> After 2 days on 1.6.0 im seeing 0.5GiB memory used. Progress for sure, but not solved.

Great to see, but I agree with you, not solved yet. I'll keep experimenting, though right now I'm out of ideas of what to try to be honest.

**Comment by JokerQyou** [comment]
Over 1.5GiB used over ~10 days with `1.6.0`.

**Comment by 0xCA** [comment]
1.7.1, definitely not fixed. Also sometimes it does a crazy thing, consuming several gigs of **video** memory. But most of the time it's just gigs of ram. Easy to see just in one day. I have a memory view opened most of the time, and sometimes app list, sorted by ram usage. Ironically, I installed it to better manage memory usage of my system.

**Comment by knackstedt** [comment]
Unfortunately I can also confirm it's still not fixed. I've been seeing it grow above 13GB over several days and suspend cycles on both ubuntu 22 and 24. I can run a heap dump or something if you tell me what tooling to use for that

**Comment by nekohayo** [comment]
Those of you who are still affected should try running the app under Valgrind (and GNOME Builder allows that with its "Run with leak detector" action), see https://developer.gnome.org/documentation/tools/valgrind.html

Apparently Valgrind is something that can be used in Rust according to [this forum thread](https://users.rust-lang.org/t/finding-memory-leaks/123557) and [that blog post](https://nnethercote.github.io/2022/01/05/rust-and-valgrind.html), which are probably relevant guides for this situation.
